---
languages: [fr_FR]
baseurl: "/"
sass:
  sass_dir: css
  style: compressed
permalink: /404.html
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
  syntax_highlighter: rouge
highlighter: rouge
gems:
- jekyll-paginate
- jekyll-seo-tag
- jemoji
exclude:
- vendor
plugins:
- jekyll-seo-tag
title: "Documentation plugins Jeedom"
description: "Documentation des plugins Jeedom développés par Michel_F."
author: "Michel_F"
image: https://mrwaloo.github.io/jeedom-plugins-doc/icon.png
social:
  name: Michel_F
  links:
    - https://mrwaloo.github.io/jeedom-plugins-doc
---
